<?php

namespace ContainerPrtad2R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H1MLPVcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.H1MLPVc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.H1MLPVc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\FormController::createPublicForm' => ['privates', '.service_locator.mIp9O3x', 'get_ServiceLocator_MIp9O3xService', true],
            'App\\Controller\\UserController::getSingleUser' => ['privates', '.service_locator.mIp9O3x', 'get_ServiceLocator_MIp9O3xService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\FormController:createPublicForm' => ['privates', '.service_locator.mIp9O3x', 'get_ServiceLocator_MIp9O3xService', true],
            'App\\Controller\\UserController:getSingleUser' => ['privates', '.service_locator.mIp9O3x', 'get_ServiceLocator_MIp9O3xService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\FormController::createPublicForm' => '?',
            'App\\Controller\\UserController::getSingleUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\FormController:createPublicForm' => '?',
            'App\\Controller\\UserController:getSingleUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
