<?php

namespace ContainerPrtad2R;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FormController' shared autowired service.
     *
     * @return \App\Controller\FormController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/FormController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/FormService.php';

        $container->services['App\\Controller\\FormController'] = $instance = new \App\Controller\FormController(new \App\Service\FormService(($container->services['doctrine'] ?? $container->load('getDoctrineService'))));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\FormController', $container));

        return $instance;
    }
}
